-- create database db2020;
USE db2020;

CREATE TABLE IF NOT EXISTS USER (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    PW VARCHAR(128) NOT NULL,
    NAME VARCHAR(15),
    BIRTH DATE,
    PHONE VARCHAR(11),
    GENDER CHAR,
    ROLE CHAR NOT NULL,
    PRIMARY KEY(ID)
    );

CREATE TABLE IF NOT EXISTS USER_SUBMITTER
        ( ID bigint(20) NOT NULL,
            PRIMARY KEY(ID),
        FOREIGN KEY(ID) REFERENCES USER(ID)
        ON UPDATE CASCADE ON DELETE CASCADE
        );

CREATE TABLE IF NOT EXISTS USER_EVALUATOR
        ( ID bigint(20) NOT NULL,
        PRIMARY KEY(ID),
        FOREIGN KEY(ID) REFERENCES USER(ID)
        ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS USER_ADMIN
        ( ID bigint(20) NOT NULL,
        PRIMARY KEY(ID),
        FOREIGN KEY(ID) REFERENCES USER(ID)
        ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS TASK_METADATA
        (TABLE_NAME VARCHAR(50) NOT NULL,
        DISPLAY_NAME VARCHAR(15) NOT NULL,
        DESCRIPTION VARCHAR(100),
        MIN_UPLOAD_CYCLE INT NOT NULL DEFAULT 30,
        ACTIVATED BIT NOT NULL DEFAULT 0,
        PASS_CRITERION INT NOT NULL DEFAULT 10,
        PRIMARY KEY(TABLE_NAME)
        );

CREATE TABLE IF NOT EXISTS RAW_FILE_METADATA
        ( TABLE_NAME VARCHAR(50) NOT NULL,
        DISPLAY_NAME VARCHAR(15) NOT NULL,
        MAPPING_SQL_QUERY VARCHAR(1000) NOT NULL,
        TASK_NAME VARCHAR(15) NOT NULL,
        PRIMARY KEY(TABLE_NAME),
        FOREIGN KEY(TASK_NAME) REFERENCES TASK_METADATA(TABLE_NAME)
        );

CREATE TABLE IF NOT EXISTS RAW_DATA_TEMPLATE
        ( RDT_ID bigint(20) NOT NULL AUTO_INCREMENT,
        RAW_DATA BLOB NOT NULL,
        PRIMARY KEY(RDT_ID)
        );

CREATE TABLE IF NOT EXISTS SUBMISSION
        ( SUBM_ID bigint(20) NOT NULL AUTO_INCREMENT,
SUBMIT_COUNT INT NOT NULL DEFAULT 0,
DURATION_INFO   TIME NOT NULL,
PARSED BIT NOT NULL,
PRIMARY KEY(SUBM_ID)
);

CREATE TABLE IF NOT EXISTS RAW_DATA_SEQ
        ( RDS_ID bigint(20) NOT NULL AUTO_INCREMENT,
        PRIMARY KEY(RDS_ID)
        );

CREATE TABLE IF NOT EXISTS PARSING_DATA_SEQ
        (PDS_ID bigint(20) NOT NULL AUTO_INCREMENT,
        TOTAL_TUPLE_COUNT INT NOT NULL DEFAULT 0,
        DUPLICATED_TUPLE_COUNT INT NOT NULL DEFAULT 0,
        PRIMARY KEY(PDS_ID)
        );

CREATE TABLE IF NOT EXISTS NULL_RATIO_PER_COLUMN
        (PDS_ID bigint(20) NOT NULL,
        NULL_RATIO REAL NOT NULL CHECK (NULL_RATIO BETWEEN 0 AND 1),
        PRIMARY KEY(PDS_ID, NULL_RATIO),
        FOREIGN KEY(PDS_ID) REFERENCES PARSING_DATA_SEQ(PDS_ID)
        );

CREATE TABLE IF NOT EXISTS PARTICIPATES_IN
        ( UID bigint(20) NOT NULL,
TABLE_NAME VARCHAR(50) NOT NULL,
STATUS CHAR NOT NULL,
PRIMARY KEY(UID, TABLE_NAME),
FOREIGN KEY(UID) REFERENCES USER_SUBMITTER(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(TABLE_NAME) REFERENCES TASK_METADATA(TABLE_NAME)
);

CREATE TABLE IF NOT EXISTS REQUESTS_NEW
        ( UID bigint(20) NOT NULL,
TABLE_NAME VARCHAR(50) NOT NULL,
RDT_ID bigint(20) NOT NULL,
PDS_ID bigint(20) NOT NULL,
STATUS CHAR NOT NULL,
PRIMARY KEY(UID, TABLE_NAME, RDT_ID),
FOREIGN KEY(UID) REFERENCES USER_SUBMITTER(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(TABLE_NAME) REFERENCES TASK_METADATA(TABLE_NAME),
FOREIGN KEY(RDT_ID) REFERENCES RAW_DATA_TEMPLATE(RDT_ID),
FOREIGN KEY(PDS_ID) REFERENCES PARSING_DATA_SEQ(PDS_ID)
);

CREATE TABLE IF NOT EXISTS SUBMITS
        ( UID bigint(20) NOT NULL,
TABLE_NAME VARCHAR(50) NOT NULL,
SUBM_ID BIGINT(20),
PRIMARY KEY(UID, TABLE_NAME),
FOREIGN KEY(UID) REFERENCES USER_SUBMITTER(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(TABLE_NAME) REFERENCES RAW_FILE_METADATA(TABLE_NAME),
FOREIGN KEY(SUBM_ID) REFERENCES SUBMISSION(SUBM_ID)
);

CREATE TABLE IF NOT EXISTS EVALUATES
( UID bigint(20) NOT NULL,
    PDS_ID bigint(20) NOT NULL,
    STATUS CHAR NOT NULL,
    P_NP BIT NOT NULL,
    RATING INT NOT NULL,
    PRIMARY KEY(UID, PDS_ID),
    FOREIGN KEY(UID) REFERENCES USER_EVALUATOR(ID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(PDS_ID) REFERENCES PARSING_DATA_SEQ(PDS_ID)
);

CREATE TABLE IF NOT EXISTS IS_ASSIGNED_TO
        ( UID bigint(20) NOT NULL,
PDS_ID bigint(20) NOT NULL,
DUE DATE NOT NULL,
PRIMARY KEY(UID, PDS_ID),
FOREIGN KEY(UID) REFERENCES USER_EVALUATOR(ID)
        ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(PDS_ID) REFERENCES PARSING_DATA_SEQ(PDS_ID)
);


CREATE TABLE IF NOT EXISTS PREV_EVALUATORS
( UID bigint(20) NOT NULL,
PDS_ID bigint(20) NOT NULL,
PREV_EVALUATOR VARCHAR(15) NOT NULL,
PRIMARY KEY(UID, PDS_ID),
FOREIGN KEY(UID) REFERENCES USER_EVALUATOR(ID)
        ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(PDS_ID) REFERENCES PARSING_DATA_SEQ(PDS_ID)
);




