version: '3'
services:

  db:
    container_name: db
    image: mariadb
    ports:
      - "3400:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db2020
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db2020
      MYSQL_USER: root
      MYSQL_PASSWORD: db2020
    volumes:
      - dbdata:/var/lib/mysql/data/
      - ./:/app

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn django_docker.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: django_docker.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
      - ./:/app
    depends_on:
      - db
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "2323:2323"
    depends_on:
      - web

volumes:
  static:
  media:
  dbdata:
  app: