# Generated by Django 3.0.8 on 2020-11-29 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='식당 이름')),
                ('atmosphere', models.IntegerField(blank=True, null=True, verbose_name='분위기')),
                ('sanitation', models.IntegerField(blank=True, null=True, verbose_name='청결')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SideDishesReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='사이드 메뉴 이름')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='가격')),
                ('portion', models.TextField(blank=True, null=True, verbose_name='양')),
                ('taste', models.IntegerField(blank=True, null=True, verbose_name='맛')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_dishes_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='음식 메뉴 이름')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='가격')),
                ('portion', models.TextField(blank=True, null=True, verbose_name='양')),
                ('taste', models.IntegerField(blank=True, null=True, verbose_name='맛')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
