# Generated by Django 3.0.8 on 2020-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mealreview_sidedishesreview_stylereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylereview',
            name='parking',
            field=models.IntegerField(blank=True, null=True, verbose_name='주차장 여부'),
        ),
        migrations.AddField(
            model_name='stylereview',
            name='toilet',
            field=models.IntegerField(blank=True, null=True, verbose_name='화장실 여부'),
        ),
        migrations.AlterModelTable(
            name='mealreview',
            table='MEAL_REVIEW',
        ),
        migrations.AlterModelTable(
            name='sidedishesreview',
            table='SIDE_DISHES_REVIEW',
        ),
        migrations.AlterModelTable(
            name='stylereview',
            table='STYLE_REVIEW',
        ),
    ]
