# Generated by Django 3.0.8 on 2020-11-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201129_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestsnew',
            options={'managed': True},
        ),
    ]
