# Generated by Django 3.0.8 on 2020-11-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201129_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestsnew',
            options={'managed': False},
        ),
    ]
